Remove unused test files
Jest fails with

```
 FAIL  src/App.test.js
  ✕ renders learn react link (34ms)

  ● renders learn react link

    TypeError: Cannot read property 'createProgram' of null

      55 |              gl = canvasRef.current.getContext("webgl");
      56 |
    > 57 |              const prog = gl.createProgram();
         |                              ^
      58 |
      59 |              let sh;
      60 |

      at initGL (src/App.js:57:19)
      at src/App.js:130:3
```

That's probably because you can't use WebGL with jsdom, so remove the
"test boilerplate".